### ISSUE TITLE
Clients' CSR and private keys are kept

### ISSUE THREAD

**Issue by acrilex1** [kyl191/ansible-role-openvpn#110]
When providing items in the clients variable, the role creates the client's private key, CSR and certificate on the target. However, the target only needs the certificate in order to add the client to the revocation list later on.

The best scenario would be to generate the clients' key on their own side, but it is out of scope of this role. However, the role should at least remove the private key, CSR and ovpn files at the end of the client_keys task.

**Comment by kyl191** [comment]
Problem is statefulness - I left the keys on disk so they don't get continually generated on every run, and updating the config file wouldn't force a full key regeneration cycle.

If you're running in a "one shot", adding and removing the client from the run list, yeah, this makes sense. 

Gate this behind something that acknowledges the one shot of config generation, and this is fine, but for the general Ansible use of "enforce state", this kind of breaks the assumptions.

**Comment by kyl191** [comment]
Closing this as stale. 

I don't understand the exact use case that clearing keys would solve. I see the concern - unencrypted keys left on disk when the server process doesn't need them isn't good security. 

As I understand it, the primary case clearing the tokens protects against is a malicious sysadmin who could plausibly grab a copy of the client config and connect with those tokens. 

But said malicious sysadmin would have access _at generation time_ anyway.

In the event of a server compromise, the server certs would have to be regenerated and the config redistributed to clients anyway - and this role allows for the simultaneous recreation of server and client certs, so there's negligible additional overhead from regenerating client certs.

Deleting the keys after generation breaks the role's expectations of idempotent config regeneration, and I don't see why that needs to change.

You could use a `post_tasks` stanza in your playbook to clean up the files that you don't want if you don't want to maintain a fork.
