### ISSUE TITLE
TLS key in client config file 

### ISSUE THREAD

**Issue by Tanis74** [kyl191/ansible-role-openvpn#113]
When the option 

> tls_auth_required

 is disabled, the tls_auth key still gets to the client config. Because of this, the Windows client cannot connect to the server.

**Comment by mabeett** [comment]
Dear Tanis,
I found this problem when the client is [OpenConnect for Android](https://play.google.com/store/apps/details?id=net.openvpn.openvpn).

I am working in a patch. In case I generate a PR Could you please test ot with the Windows client you said?

**Comment by kyl191** [comment]
Solved in #142, closing this
