### ISSUE TITLE
Centos 8 seems ok

### ISSUE THREAD

**Issue by Sispheor** [kyl191/ansible-role-openvpn#118]
I just tested the role on a Centos8 VM and it seems to work perfectly.
Maybe you can add this OS to the list of supported one. And add it to Travis Ci as well.

**Comment by 13rentgen** [comment]
It's not ok, cause of openvpn-auth-ldap package is not available for Centos8

**Comment by kyl191** [comment]
It was OK, LDAP wasn't working but I don't consider it crucial. 

Added CentOS 8 to the new CI, and will add it to the readme.

**Comment by kyl191** [comment]
Addressed in #130

**Comment by Sispheor** [comment]
For LDAP I guess it's just a matter of package name.
