### ISSUE TITLE
/etc/init.d/iptables-persistent-save doesn't exist

### ISSUE THREAD

**Issue by ja-heller** [kyl191/ansible-role-openvpn#12]
When I run the playbook I get:

> TASK [etc : iptables - save everything (Debian/Ubuntu)] ************************
> fatal: [vpn_germany1]: FAILED! => {"changed": false, "cmd": "/etc/init.d/iptables-persistent save", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}

I verified the installation of iptables-persistent:

> root@DEBIAN-TEST:~# apt-get install iptables-persistent
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> iptables-persistent is already the newest version (1.0.4).
> The following packages were automatically installed and are no longer required:
>   linux-headers-4.4.0-21 linux-headers-4.4.0-21-generic linux-headers-4.4.0-31
>   linux-headers-4.4.0-31-generic linux-image-4.4.0-21-generic
>   linux-image-4.4.0-31-generic linux-image-extra-4.4.0-21-generic
>   linux-image-extra-4.4.0-31-generic
> Use 'apt autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 79 not upgraded.

**Comment by kyl191** [comment]
Which version of Debian is this?

**Comment by robotmay** [comment]
I've also just received this error, on Ubuntu 16.04 x64 for me.

**Comment by kyl191** [comment]
Ok, I'm going to try a fairly exhaustive test of the playbook on EC2 in #26 to see if I can reproduce this. (My standard env is Fedora, my apologies for not being on the ball for Debian + Ubuntu)

**Comment by kyl191** [comment]
@ja-heller I've updated the playbook to handle ufw in addition to iptables, and be smarter about handling saving rules. I've tested it with the version of Debian available in AWS (after installing `ufw`, see #26) and it works. If you're still interested, could you try again?

@robotmay I've updated the playbook to handle ufw, so Ubuntu 16.04 no longer falls back to using iptables. If you're still interested, could you try again?

**Comment by kyl191** [comment]
Going to assume everything is ok.
