### ISSUE TITLE
can you update README ?

### ISSUE THREAD

**Issue by Giancarlo1974** [kyl191/ansible-role-openvpn#133]
I need some examples on how to use your repository for:
1) install the server,
2) create 2 users (user and password)
3) install a client to use user1 and password1

**Comment by kyl191** [comment]
For 1, it's provided in the readme: https://github.com/kyl191/ansible-role-openvpn#example-playbook

For 2 and 3, I don't know how to configure openvpn to use a user/password, but you should be able to get it working by setting `openvpn_addl_server_options` and `openvpn_addl_client_options` as necessary.

Good luck.
