### ISSUE TITLE
CRL not working as intended.

### ISSUE THREAD

**Issue by MvLoonsl** [kyl191/ansible-role-openvpn#145]
templates/ca.conf.j2: 

  default_crl_days = 30

Which means that upon "gencrl" "lastupdate" is set to the run timestamp and "nextupdate" is set to 30 days in the future.
After that, nothing in ansible-role-openvpn seems to update "nextupdate" other than doing an actual manual revoke / manual running revoke.sh .
When more than 30 days have passed since either the initial creation or the last revoke,
openvpn 2.4 or later then freaks out because the CRL has expired and doesn't let anyone connect with crl-verify enabled.  (https://community.openvpn.net/openvpn/wiki/CertificateRevocationListExpired)

templates/crl-cron.sh.j2:
only checks there's a less than 10 days difference between "lastupdate" and "nextupdate", but my impression is that difference will _always_ be "default_crl_days", so it never triggers the regenerate/renew.
Was the intention to do a check of current timestamp (date +%s) vs "nextupdate" instead?
Straight up having crl-cron.sh run revoke.sh without the "less than 10 days" check should probably work OK instead, since that would do a weekly regenerate/renew instead of 20-27 days after the last revoke/renew.
(keeping the short renew period should from what I could google be a bit safer (shorter caching, shorter keeping antique revoked cerificates listed in it) than the often used workaround of throwing default_crl_days to 3650 (10 years)...) 

templates/server.conf.j2:

 

>  {% if openvpn_crl_path is defined %}
>   crl-verify {{openvpn_crl_path}}
>   {% endif %}
>   {% if openvpn_use_crl|bool %}
>   crl-verify {{openvpn_key_dir}}/ca-crl.pem
>   {% endif %}

I'm guessing that was meant to be "openvpn_use_crl" as boolean on/off toggle with
"{{openvpn_key_dir}}/ca-crl.pem" as default if "openvpn_crl_path" _isn't_ defined?
In its current form it writes 2 "crl-verify" lines if both options are defined...

(I'm decent at reading/decoding programming languages, but a newbie at writing ansible/jinja2, so unfortunately couldn't put the above in the form of a pull request...)

**Comment by jbeyerstedt** [comment]
We have run in the same issue, that the CRL isn't updated by the crl-cron.sh script before it expired.

I also think, that checking, if the nextUpdate time is in the near future is enough instead of comparing the next and last update times. I'll open a PR with that change.
