### ISSUE TITLE
Allow TCP management interface

### ISSUE THREAD

**Issue by georborodin** [kyl191/ansible-role-openvpn#180]
If you try make management interface listen via TCP (setting openvpn_management_bind to something like "localhost 7505"), the resulting config still contains management-client-user option, which results in OpenVPN server failing to start with this error message:
`Options error: --management-client-(user|group) can only be used on unix domain sockets`

**Comment by kyl191** [comment]
This only happens if you change `openvpn_management_bind` to TCP, because the default `openvpn_management_client_user` is set to `root`.

I expect this would be fixed by setting `openvpn_management_client_user: ~`.
