### ISSUE TITLE
Error on default openvpn_client_config_dir

### ISSUE THREAD

**Issue by animalillo** [kyl191/ansible-role-openvpn#197]
The default value for the `openvpn_client_config_dir` is `ccd` and that does not exist. I have recently updated the module and it broke the vpn server for a while hehehe.

Nothing too big, but a little improvement

Anyhow! thank you for the great work! This module is pretty useful!

**Comment by kyl191** [comment]
Was wondering what you were talking about, but I think I was able to repro the problem
```
Options error: --client-config-dir fails with 'ccd': No such file or directory (errno=2)
Options error: Please correct these errors.
```
