### ISSUE TITLE
How to add new server in the openvpn realm, how to make tunnel 

### ISSUE THREAD

**Issue by arpitcoder** [kyl191/ansible-role-openvpn#198]
I have a new server which i have created in the same network where my open vpn server is running how and where should i make changes in order to make a tunneling so that when i connect to the openvpn i can connect to the server.

**Comment by kyl191** [comment]
This is outside the scope of the role since it's asking how to configure OpenVPN. 

Once you figure it out you can translate it to the role, but I can't support OpenVPN issues.
