### ISSUE TITLE
Recent Ansible changes compatibility

### ISSUE THREAD

**Issue by ricardclau** [kyl191/ansible-role-openvpn#200]
Hi, first of all, thanks for this great role, I have used with a lot of clients successfully

I am facing issues with recent versions of Ansible, there is the include directive being no longer available and there are more changes comming regarding the subnet functions, etc...

I can work on adapting all these (have actually done it locally) but not sure if you would consider publishing a newer version or just lost interest in the project (which is totally understandable BTW!)

Please let me know @kyl191 and thanks again for the role

**Comment by Nmishin** [comment]
Hi @ricardclau!
I forked this role some time ago and plan to work on it with my friends, and I think it will be super if you can join to our small team. What do you think?
https://github.com/aovpn/ansible-role-openvpn

**Comment by kyl191** [comment]
@ricardclau if you have more details about changes to subnet functions, feel free to open a new issue.

I don't see a roadmap for ansible-core 2.18 yet: https://docs.ansible.com/ansible/latest/roadmap/ansible_core_roadmap_index.html
