### ISSUE TITLE
Optionally use MASQUERADE instead of SNAT?

### ISSUE THREAD

**Issue by daniellandau** [kyl191/ansible-role-openvpn#50]
I want to use OpenVPN to talk from the server to clients (clients are behind NAT behind a dynamic IP address). It turned out that I needed MASQUERADE instead of SNAT to achieve that, how would you feel about adding an option for that? I can do the actual work if it's something you'd accept.

**Comment by kyl191** [comment]
Hi,
Sorry for taking a while to get back to you.

It's a pretty fundamental change, so it would definitely have to be gated behind an option. Since you have something working, I'll probably accept it, though I won't guarantee it until I see the code.
