### ISSUE TITLE
Setup autovpn autostart failing 

### ISSUE THREAD

**Issue by jhagege** [kyl191/ansible-role-openvpn#68]
Great work !
Just having a small issue at the end. Any clue ? 
On Ubuntu 16.04 LTS

> TASK [kyl191.openvpn : Setup openvpn auto-start & start] ************************************************************************************************************************************************************************************************************
> fatal: [47.254.156.204]: FAILED! => {"changed": false, "msg": "Unable to start service openvpn@openvpn_udp_1194.service: Job for openvpn@openvpn_udp_1194.service failed because the control process exited with error code. See \"systemctl status openvpn@openvpn_udp_1194.service\" and \"journalctl -xe\" for details.\n"}

**Comment by jhagege** [comment]
If it helps anyhow..
![image](https://user-images.githubusercontent.com/7504908/43850503-c9095db4-9b40-11e8-8dfb-ca0238d26ce2.png)

**Comment by shumkov** [comment]
I think the problem is:
```
-- Unit openvpn@openvpn_udp_1194.service has begun starting up.
Sep 15 01:24:47 vpn ovpn-openvpn_udp_1194[4692]: Options error: Unrecognized option or missing parameter(s) in /etc/openvpn/openvpn_udp_1194.conf:27: compress (2.3.10)
Sep 15 01:24:47 vpn ovpn-openvpn_udp_1194[4692]: Use --help for more information.
Sep 15 01:24:47 vpn systemd[1]: openvpn@openvpn_udp_1194.service: Control process exited, code=exited status=1
Sep 15 01:24:47 vpn systemd[1]: Failed to start OpenVPN connection to openvpn_udp_1194.
-- Subject: Unit openvpn@openvpn_udp_1194.service has failed
```
OpenVPN 2.3.10 doesn't support compress option.

**Comment by jhagege** [comment]
Thanks!

**Comment by ehime** [comment]
@jhagege Can you create a PR with this? It's also breaking my build...

**Comment by kyl191** [comment]
This pulls in the official openvpn build instead of whatever is in the 16.04 repo, right? I don't run Ubuntu, so this would have to be a PR.

In any case, this is stale, I'm closing it to clean up this repo.

Reopen it if you want, thanks.
