### ISSUE TITLE
LDAP configuration

### ISSUE THREAD

**Issue by deveshmehta** [kyl191/ansible-role-openvpn#70]
Hi Team,

I tried to configure the ldap authentication but auth/ldap.conf file is not getting updated.

Below is my setup-openvpn.yml file. Could you please suggest what is wrong in it.

---
- hosts: vpn01
  become: true
  gather_facts: true
  roles:
    - role: kyl191.openvpn
      openvpn_port: 1194
      clients:
        - client1
      openvpn_push:
        - route 10.20.30.0 255.255.255.225
        - route 10.x.x.0 255.255.255.0
        - dhcp-option DNS 10.x.x.46
      iptables_service: firewalld
      openvpn_use_ldap: true
      ldap:
        url: 'ldaps://ldap01'
        bind_dn: cn=Manager,dc=example,dc=uk
        bind_password: test
        tls_ca_cert_file: /etc/openldap/certs/ca_certs.pem
        base_dn: dc=example,dc=uk
        search_filter: (&(uid=%u))
        require_group: true
        group_base_dn: ou=vpn,dc=example,dc=uk
        group_search_filter: (|(cn=DevOps)(cn=users))

**Comment by kyl191** [comment]
LDAP was a contribution by the community, I don't have any setup to test it on, so I can't help you there unfortunately.
