### ISSUE TITLE
compress lzo is deprecated in OpenVPN 2.4 and removed in 2.5

### ISSUE THREAD

**Issue by joekohlsdorf** [kyl191/ansible-role-openvpn#73]
The template sets `compress lzo`, this configuration option is deprecated in 2.4 and was removed in 2.5.

I suggest to make including this setting configurable and maybe not activate it by default. Maybe setting lz4 compression should be made possible.

**Comment by digitalist** [comment]
https://community.openvpn.net/openvpn/wiki/VORACLE
andd by the way, compress should be disabled by default
