### ISSUE TITLE
Timeout errors

### ISSUE THREAD

**Issue by mevansLA** [kyl191/ansible-role-openvpn#84]
Hi all,

I'm having a few issues, when running this playbook I'm getting the following error when running the handlers at the end (specifically restart openvpn & save iptables).
ERROR! Timeout (12s) waiting for privilege escalation prompt
and when I tried running using "-c paramiko" i got this:
UNREACHABLE! => {"changed": false, "msg": "Authentication timeout.", "unreachable": true}

Any ideas what's going on here?
I can manually SSH to the server and perform both tasks (restart openvpn & save iptables) with no issue.

**Comment by kyl191** [comment]
This is stale, I'm closing it to clean up this repo.

Off hand it looks like the user you're using needs a password for sudo, which is more an ansible issue than an issue with this role.
