### ISSUE TITLE
UFW default policy for input fixed as 'allow'

### ISSUE THREAD

**Issue by elektro-wolle** [kyl191/ansible-role-openvpn#86]
In`ansible-role-openvpn/tasks/ufw.yml` the default input policy is hardcoded to 'allow'.

**Comment by kyl191** [comment]
@elektro-wolle what should it be instead?

**Comment by elektro-wolle** [comment]
Default to 'deny'? Or making it configurable with default to 'allow' (not breaking previous installations).

**Comment by robvadai** [comment]
Default definitely shouldn't be allow. As a workaround I had to apply a role after this role that just sets the default to deny. Would be great if this could be configured from here.

**Comment by kyl191** [comment]
I don't personally run Ubuntu, this will have to be a PR.
