### ISSUE TITLE
Cannot detect already installed ufw firewall

### ISSUE THREAD

**Issue by robvadai** [kyl191/ansible-role-openvpn#93]
Deployment fails with `fatal: [xxxxxxxxx.com]: FAILED! => {"changed": false, "msg": "No firewall detected, install one before proceeding (firewalld||ufw||iptables)"}`

`ufw` was installed from https://github.com/weareinteractive/ansible-ufw

**Comment by kyl191** [comment]
https://github.com/kyl191/ansible-role-openvpn/commit/ca6470e00dcb526ed4266920f6ed5dad46dc7710 was just merged, try again?
